name: ipapi
description: Geolocation plugin for Flutter based on ip-api.com. Supports both free and pro access.
version: 2.0.1
repository: https://github.com/mk-dev-1/ipapi
tags:
  - geolocation
  - country
  - ip
  - lookup
  - ip-api

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  http: ^1.2.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_lints: ^5.0.0
  json_serializable: ^6.3.2
  build_runner: ^2.2.1
  test: ^1.25.4
  collection: ^1.18.0
