name: ipapi
description: Geolocation plugin for Flutter based on ip-api.com. Supports both free and pro access.
version: 1.0.2
repository: https://github.com/mk-dev-1/ipapi

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  http: ^1.2.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_lints: ^3.0.2
  json_serializable: ^6.3.2
  build_runner: ^2.2.1
